---

- name: HALYARD ON DOCKER | Create directories
  file:
    path: ~/.hal
    state: directory
    owner: "{{ halyard_user }}"
    group: "{{ halyard_group }}"
    mode: 0755

- name: HALYARD ON DOCKER | Run the container
  docker_container:
    state: started
    name: halyard
    image: gcr.io/spinnaker-marketplace/halyard:stable
    recreate: yes
    auto_remove: yes
    interactive: yes
    tty: yes
    exposed_ports:
      - 8084
      - 9000
    volumes:
      - "~/.hal:/home/{{ halyard_user }}/.hal"
