---

- name: HALYARD | Manage user
  import_tasks: user.yml

- name: HALYARD | Deploy on Operating System
  import_tasks: baremetal.yml
  when: halyard_platform == 'baremetal'

- name: HALYARD | Deploy on Docker
  import_tasks: docker.yml
  when: halyard_platform == 'docker'
